# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12a9a541f57b718fb218a86f2246cec5875c95ff79ffe9e6ceced469884b3c2b2dad20caa4fa0fb145b5408b02836b59378691ba9132fd8a8f22ad4e912178fb

test:
  secret_key_base: 5b2cbe6b6484365a1d0198f2aa7aef29d86abe3652f70dfcda8157b079cd3ab24a6a866e47928729cf22d0187e0c387068655d6d8cf94bb684395e7753237310

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
